apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
  name: my-mirror-maker-2
spec:
  version: 3.6.0
  replicas: 1
  connectCluster: "B" # Must be the target custer
  clusters:
  - alias: "A" # Source cluster
    bootstrapServers: host.docker.internal:9092
  - alias: "B" # Target cluster
    bootstrapServers: host.docker.internal:9093
    config:
      # -1 means it will use the default replication factor configured in the broker
      config.storage.replication.factor: -1
      offset.storage.replication.factor: -1
      status.storage.replication.factor: -1
  mirrors:
  - sourceCluster: "A"
    targetCluster: "B"
    sourceConnector:
      tasksMax: 2
      config:
        # -1 means it will use the default replication factor configured in the broker
        replication.factor: -1
        offset-syncs.topic.replication.factor: -1
        sync.topic.acls.enabled: "false"
        replication.policy.class: "org.apache.kafka.connect.mirror.IdentityReplicationPolicy"
        topics.exclude: ".*[\\-\\.]internal, .*\\.replica"
    checkpointConnector:
      tasksMax: 1
      config:
        # -1 means it will use the default replication factor configured in the broker
        checkpoints.topic.replication.factor: -1
        replication.policy.class: "org.apache.kafka.connect.mirror.IdentityReplicationPolicy"
        sync.group.offsets.enabled: "true"
        sync.group.offsets.interval.seconds: 5
        emit.checkpoints.interval.seconds: 5
        refresh.groups.interval.seconds: 60
    topicsPattern: ".*"
    groupsPattern: ".*"
    topicsExcludePattern: ".*[\\-\\.]internal, .*\\.replica"